services:
  frontend:
    container_name: thinklingo-frontend
    build:
      args:
        - PUBLIC_URL=/
        - REACT_APP_AUTH_TOKEN=${AUTH_TOKEN}
    networks:
      - default
      - web

  backend:
    container_name: thinklingo-backend
    networks:
      - default
      - web

networks:
  web:
    external: true
